# Generated by Django 3.1.7 on 2021-03-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0002_auto_20210301_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='description_kg',
            field=models.TextField(max_length=350, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='card',
            name='description_ru',
            field=models.TextField(max_length=350, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='card',
            name='title_kg',
            field=models.CharField(max_length=150, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='card',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Заголовок'),
        ),
    ]
